"""add persons and bookings tables

Revision ID: 938ac8b2145d
Revises: 
Create Date: 2026-06-04 17:00:08.792877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '938ac8b2145d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passengers',
    sa.Column('passenger_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('age', sa.String(), nullable=True),
    sa.Column('sib_sp', sa.String(), nullable=True),
    sa.Column('parch', sa.String(), nullable=True),
    sa.Column('survived', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('passenger_id')
    )
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('passenger_id', sa.String(), nullable=True),
    sa.Column('pclass', sa.String(), nullable=True),
    sa.Column('ticket', sa.String(), nullable=True),
    sa.Column('fare', sa.String(), nullable=True),
    sa.Column('cabin', sa.String(), nullable=True),
    sa.Column('embarked', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['passenger_id'], ['passengers.passenger_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('titanic_records')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('titanic_records',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('passenger', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('survived', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('pclass', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('age', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sibsp', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('parch', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ticket', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('fare', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cabin', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('embarked', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('titanic_records_pkey'))
    )
    op.drop_table('bookings')
    op.drop_table('passengers')
    # ### end Alembic commands ###
